""" Window """
SCREEN_TITLE = "ZoteBoat"
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

""" Sprites """
CELL_SIZE = 128 # SPRITE_SIZE
PLAYER_SCALING = 0.5

""" Physics """
# --- Player ---
PLAYER_MAX_VERTICAL_VELOCITY = 1000
PLAYER_MAX_HORIZONTAL_VELOCITY = 800
PLAYER_MASS = 5
PLAYER_FORCE = 500
PLAYER_AIR_FORCE = 300

# --- General ---
DEFAULT_FRICTION = 1 
LOW_FRICTION = 0.4

