# --- Window ---
SCREEN_TITLE = "ZoteBoat"
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# --- Sprites ---
CELL_SIZE = 128
TILE_SCALING = 0.5

RIGHT_FACING = 1
LEFT_FACING = -1
UP_FACING = -1
DOWN_FACING = 1
SIDE_FACING = 0

# --- Player ---
P_ATTACK_COOLDOWN = 0.25
P_ATTACK_DAMAGE = 1
P_HEALTH = 5
P_INV_TIME = 1.3

# --- Physics ---
GRAVITY = 1
PLAYER_MOVEMENT_SPEED = 5
PLAYER_JUMP_SPEED = 20

# --- Maps ---
DEFAULT_MAP = "map_1"
DEFAULT_SPAWN = (200, 440)